name: BinaryBuilder
on: [push, create]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-linux-gnu
          - x86_64-linux-gnu
          - aarch64-linux-gnu
          - arm-linux-gnueabihf
          - powerpc64le-linux-gnu
          # - i686-linux-musl
          # - x86_64-linux-musl
          # - aarch64-linux-musl
          # - arm-linux-musleabihf
          - x86_64-apple-darwin14
          - x86_64-unknown-freebsd11.1
          # - i686-w64-mingw32
          - x86_64-w64-mingw32
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.9"
      - name: Setup BinaryBuilder
        env:
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: |
          julia --color=yes -e 'using Pkg; pkg"add BinaryBuilder; build"'
          julia --color=yes ./.github/build_tarballs.jl --verbose ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: products/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
