name: CD
on:
  push:
    branches:
      - main
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    name: GitHub artifacts
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.9"
      - name: Setup BinaryBuilder
        env:
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: |
          julia --color=yes -e 'using Pkg; pkg"add BinaryBuilder; build"'
          julia --color=yes ./.github/build_tarballs.jl --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: products/
      - name: Publish tarball
        uses: softprops/action-gh-release@v1
        with:
          files: products/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
